package Community_parking_fee;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

public class Add_casual_user extends javax.swing.JFrame {

    String username;
    public Add_casual_user(String username) {
	 	this.setLocation(600,300);
    	this.username = username;
    	setTitle("社区停车收费系统");
    	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        id_text = new javax.swing.JTextField();
        phone_text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        return_button = new javax.swing.JButton();
        post_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N
        jLabel1.setText("临时用户注册");

        id_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_textActionPerformed(evt);
            }
        });

        phone_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_textActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("幼圆", 1, 15)); // NOI18N
        jLabel2.setText("车牌号：");

        jLabel3.setFont(new java.awt.Font("幼圆", 1, 15)); // NOI18N
        jLabel3.setText("手机号：");

        return_button.setText("返回");
        return_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_buttonActionPerformed(evt);
            }
        });

        post_button.setText("提交");
        post_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                post_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20)
                        .addComponent(id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(return_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(post_button))
                            .addComponent(phone_text))))
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(phone_text, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(return_button)
                    .addComponent(post_button))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void id_textActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void phone_textActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void return_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    	this.dispose();
    	java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Main(username).setVisible(true);
			}
		});
    } 
    String car_id = "";
    String name = "*";
    String phone = "";
    String address = "*";
    int flag = 0;
    void get_text() {
    	this.car_id = id_text.getText();
    	this.phone = phone_text.getText();
    	add_user();
    }
    void add_user() {
    	if(!car_id.equals("")&& !phone.equals("")){
    		Connection con = (new Connect_db()).get_con();
        	Statement sql = null;
        	ResultSet res;
        	try {
        		sql = con.createStatement();
        		String table_carid = "'"+car_id+"'";
        		res = sql.executeQuery("select * from users where car_id="+table_carid);
        		if(!res.next()) {
        			res.close();
        			String insertsql = "insert into users values(?,?,?,?,?,?);";
        			PreparedStatement psta = con.prepareStatement(insertsql);
        			psta.setString(1, this.car_id);
        			psta.setString(2, this.name);
        			psta.setString(3, this.phone);
        			psta.setString(4, this.address);
        			psta.setInt(5, this.flag);
        			psta.setInt(6, 0);
        			psta.addBatch();
        			psta.executeBatch();
        			psta.close();
        			con.close();
        			this.dispose();
        			java.awt.EventQueue.invokeLater(new Runnable() {
        				public void run() {
        					new Main(username).setVisible(true);
        				}
        			});
        		}
        		else {
        			res.close();
        			this.dispose();
        			java.awt.EventQueue.invokeLater(new Runnable() {
        				public void run() {
        					new Add_admin_fail(username).setVisible(true);
        				}
        			});
        		}
        	}catch(Exception e)
        	{
        		System.out.println(e);
        	}
    	}
    	else {
    		this.dispose();
    		java.awt.EventQueue.invokeLater(new Runnable() {
    			public void run() {
    				new Add_admin_fail(username).setVisible(true);
    			}
    		});
    	}
    }

    private void post_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    	get_text();
    }                                           



    // Variables declaration - do not modify                     
    private javax.swing.JTextField id_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField phone_text;
    private javax.swing.JButton post_button;
    private javax.swing.JButton return_button;
    // End of variables declaration                   
}
