package Community_parking_fee;
import java.sql.*;
public class Del_sure extends javax.swing.JFrame {

    /**
     * Creates new form Del_sure
     */
	String username;
	String id ;
	String uusername;
	String car_id;
	String telephone;
	String home_address;
	String flag="否";
	String park_flag="无";
	public Del_sure(String username,int id, String car_id,String uusername,String telephone
			,String home_address, int flag,int park_flag) {
	 	this.setLocation(600,300);
		this.username = username;
		this.id = String.valueOf(id);
		this.uusername = uusername;
		this.car_id = car_id;
		this.telephone = telephone;
		this.home_address = home_address;
		if(flag==1) {
			this.flag = "是";
			this.park_flag = "有";
		}
		setTitle("社区停车收费系统");
        initComponents();
    	id_text.setText(this.id);
    	car_id_text.setText(this.car_id);
    	username_text.setText(this.uusername);
    	phone_text.setText(this.telephone);
    	address_text.setText(this.home_address);
    	flag_text.setText(this.flag);
    	park_flag_text.setText(this.park_flag);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        id_text = new javax.swing.JLabel();
        car_id_text = new javax.swing.JLabel();
        username_text = new javax.swing.JLabel();
        phone_text = new javax.swing.JLabel();
        address_text = new javax.swing.JLabel();
        flag_text = new javax.swing.JLabel();
        park_flag_text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N
        jLabel1.setText("用户编号：");

        jLabel2.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N
        jLabel2.setText("车牌号码：");

        jLabel3.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N
        jLabel3.setText("用户姓名：");

        jLabel4.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N
        jLabel4.setText("联系电话：");

        jLabel5.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N
        jLabel5.setText("家庭地址：");

        jLabel6.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N
        jLabel6.setText("是否临时用户：");

        jLabel7.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N
        jLabel7.setText("是否拥有车位：");

        jButton1.setText("返回");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("确定删除");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        id_text.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N

        car_id_text.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N

        username_text.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N

        phone_text.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N

        address_text.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N

        flag_text.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N

        park_flag_text.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(car_id_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(id_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(username_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(phone_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(address_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flag_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(park_flag_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(car_id_text, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(username_text, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(phone_text, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(address_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(flag_text, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(park_flag_text, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	this.dispose();
    	java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Del_user(username).setVisible(true);
            }
        });
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	try {
    			String delsql = "delete from users where car_id = '"+this.car_id+"'";
    			Connection conn = (new Connect_db()).get_con();
    			Statement sta = conn.createStatement();
    			sta.executeUpdate(delsql);	//执行并更新数据库数据
    			sta.close();
    			conn.close();
    			this.dispose();
    	    	java.awt.EventQueue.invokeLater(new Runnable() {
    	            public void run() {
    	                new Main(username).setVisible(true);
    	            }
    	        });
    		}catch(Exception e) {
    		System.out.println(e);
    	}
    }                                        

    // Variables declaration - do not modify                     
    private javax.swing.JLabel address_text;
    private javax.swing.JLabel car_id_text;
    private javax.swing.JLabel flag_text;
    private javax.swing.JLabel id_text;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel park_flag_text;
    private javax.swing.JLabel phone_text;
    private javax.swing.JLabel username_text;
    // End of variables declaration                   
}
