package Community_parking_fee;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

public class Show_message extends javax.swing.JFrame {

    /**
     * Creates new form Show_message
     */
	String username;
    public Show_message(String username) {
	 	this.setLocation(600,300);
    	this.username = username;
    	setTitle("社区停车收费系统");
    	f();
    	initComponents();
    	num_text.setText("共有："+xxx+"  条留言");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        num_text = new javax.swing.JLabel();
        del_button = new javax.swing.JButton();
        return_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            oobject,
            new String [] {
                "序号", "手机号", "留言时间", "留言内容"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        num_text.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N

        del_button.setText("删除留言");
        del_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_buttonActionPerformed(evt);
            }
        });

        return_button.setText("返回");
        return_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(num_text, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202)
                        .addComponent(del_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(return_button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(del_button)
                        .addComponent(return_button))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(num_text, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>                        

    private void del_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	this.dispose();
    	java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Del_message(username).setVisible(true);
            }
        });
    }                                          

    private void return_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    	this.dispose();
    	java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main(username).setVisible(true);
            }
        });
    }       
    int xxx;
    void f() {
    	try {
    		Connection con = (new Connect_db()).get_con();
            Statement statement = con.createStatement(); //创建执行对象
            String sql=null;
            String res_sql=null;
            res_sql = "select count(*) from message_list ";
            sql = "select *from message_list order by create_time desc";
            ResultSet res_count = statement.executeQuery(res_sql);
            res_count.next();
            xxx = res_count.getInt(1);
            res_count.close();
            ResultSet rs = statement.executeQuery(sql);
            int i = 0;
            oobject = new Object[xxx][4];
            while(rs.next()) {
            	oobject[i][0] = rs.getInt(1);
            	oobject[i][1] = rs.getString(3);
            	oobject[i][2] = rs.getString(4);
            	oobject[i][3] = rs.getString(2);
            	i++;
            }
            rs.close();
            statement.close();
        } catch (Exception e) {
        	System.out.println(e);
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton del_button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel num_text;
    private javax.swing.JButton return_button;
    Object oobject[][]=null;
    // End of variables declaration                   
}

